exec(open("Crohn\'s disease.py",'r',encoding='UTF8').read())
print("크론병 업데이트 완료")
exec(open("Cushing's syndrome.py",'r',encoding='UTF8').read())
print("쿠싱병 업데이트 완료")
exec(open("dilated cardiomyopathy.py",'r',encoding='UTF8').read())
print("확장성 심근병증 업데이트 완료")
exec(open("Guillian Barre syndrome.py",'r',encoding='UTF8').read())
print("길랭 - 바레 업데이트 완료")
exec(open("Haemophilia.py",'r',encoding='UTF8').read())
print("혈우병(제 8,9인자)업데이트 완료")
exec(open("idiopathic pulmonary fibrosis.py",'r',encoding='UTF8').read())
print("특발성 폐섬유화증 업데이트 완료")
exec(open("MoyaMoya.py",'r',encoding='UTF8').read())
print("모야모야 병 업데이트 완료")
exec(open("multiplesclerosis.py",'r',encoding='UTF8').read())
print("다발성 경화증 업데이트 완료")
exec(open("myasthenia gravis.py",'r',encoding='UTF8').read())
print("중증근무력증 업데이트 완료")
exec(open("Systemic lupus erythematosus.py",'r',encoding='UTF8').read())
print("전신홍반루푸스 업데이트 완료")